
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action c_CreateGameAction;
	private global::Gtk.Action c_CreateGUIAction;
	private global::Gtk.Action c_CreateConsoleAction;
	private global::Gtk.Action c_CreateWebsiteAction;
	private global::Gtk.Action c_CreateLibraryAction;
	private global::Gtk.Action c_CreateModuleAction;
	private global::Gtk.Action c_RegenerateAction;
	private global::Gtk.Action c_CreateExternalAction;
	private global::Gtk.Action c_CreateTestsAction;
	private global::Gtk.Action c_CreateContentAction;
	private global::Gtk.VBox c_VerticalBox1;
	private global::Gtk.Toolbar c_Toolbar;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView c_ProjectTreeView;
	private global::Gtk.Label c_CreateMessageLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.c_CreateGameAction = new global::Gtk.Action ("c_CreateGameAction", null, global::Mono.Unix.Catalog.GetString ("Create Protogame Project"), "xna");
		w1.Add (this.c_CreateGameAction, null);
		this.c_CreateGUIAction = new global::Gtk.Action ("c_CreateGUIAction", null, global::Mono.Unix.Catalog.GetString ("Create GUI Project"), "gui");
		w1.Add (this.c_CreateGUIAction, null);
		this.c_CreateConsoleAction = new global::Gtk.Action ("c_CreateConsoleAction", null, global::Mono.Unix.Catalog.GetString ("Create Console Project"), "console");
		w1.Add (this.c_CreateConsoleAction, null);
		this.c_CreateWebsiteAction = new global::Gtk.Action ("c_CreateWebsiteAction", null, global::Mono.Unix.Catalog.GetString ("Create Website Project"), "website");
		w1.Add (this.c_CreateWebsiteAction, null);
		this.c_CreateLibraryAction = new global::Gtk.Action ("c_CreateLibraryAction", null, global::Mono.Unix.Catalog.GetString ("Create Library Project"), "library");
		w1.Add (this.c_CreateLibraryAction, null);
		this.c_CreateModuleAction = new global::Gtk.Action ("c_CreateModuleAction", null, global::Mono.Unix.Catalog.GetString ("Create Submodule"), "module");
		w1.Add (this.c_CreateModuleAction, null);
		this.c_RegenerateAction = new global::Gtk.Action ("c_RegenerateAction", null, global::Mono.Unix.Catalog.GetString ("Regenerate MonoDevelop Projects"), "regenerate");
		w1.Add (this.c_RegenerateAction, null);
		this.c_CreateExternalAction = new global::Gtk.Action ("c_CreateExternalAction", null, global::Mono.Unix.Catalog.GetString ("Create External Project"), "external");
		w1.Add (this.c_CreateExternalAction, null);
		this.c_CreateTestsAction = new global::Gtk.Action ("c_CreateTestsAction", null, global::Mono.Unix.Catalog.GetString ("Create Test Project"), "test");
		w1.Add (this.c_CreateTestsAction, null);
		this.c_CreateContentAction = new global::Gtk.Action ("c_CreateContentAction", null, global::Mono.Unix.Catalog.GetString ("Create Content Project"), "content");
		w1.Add (this.c_CreateContentAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Module Manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.c_VerticalBox1 = new global::Gtk.VBox ();
		this.c_VerticalBox1.Name = "c_VerticalBox1";
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='c_Toolbar'><toolitem name='c_CreateGameAction' action='c_CreateGameAction'/><toolitem name='c_CreateGUIAction' action='c_CreateGUIAction'/><toolitem name='c_CreateConsoleAction' action='c_CreateConsoleAction'/><toolitem name='c_CreateWebsiteAction' action='c_CreateWebsiteAction'/><toolitem name='c_CreateLibraryAction' action='c_CreateLibraryAction'/><toolitem name='c_CreateTestsAction' action='c_CreateTestsAction'/><toolitem name='c_CreateContentAction' action='c_CreateContentAction'/><toolitem name='c_CreateExternalAction' action='c_CreateExternalAction'/><toolitem name='c_CreateModuleAction' action='c_CreateModuleAction'/><toolitem name='c_RegenerateAction' action='c_RegenerateAction'/></toolbar></ui>");
		this.c_Toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/c_Toolbar")));
		this.c_Toolbar.Name = "c_Toolbar";
		this.c_Toolbar.ShowArrow = false;
		this.c_Toolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.c_Toolbar.IconSize = ((global::Gtk.IconSize)(1));
		this.c_VerticalBox1.Add (this.c_Toolbar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.c_Toolbar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.c_ProjectTreeView = new global::Gtk.TreeView ();
		this.c_ProjectTreeView.CanFocus = true;
		this.c_ProjectTreeView.Name = "c_ProjectTreeView";
		this.GtkScrolledWindow.Add (this.c_ProjectTreeView);
		this.c_VerticalBox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.GtkScrolledWindow]));
		w4.Position = 1;
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.c_CreateMessageLabel = new global::Gtk.Label ();
		this.c_CreateMessageLabel.Name = "c_CreateMessageLabel";
		this.c_CreateMessageLabel.Xpad = 10;
		this.c_CreateMessageLabel.Ypad = 5;
		this.c_CreateMessageLabel.Xalign = 0F;
		this.c_CreateMessageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("(to be replaced)");
		this.c_VerticalBox1.Add (this.c_CreateMessageLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.c_CreateMessageLabel]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.c_VerticalBox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 479;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
