
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action c_RegenerateAction;
	private global::Gtk.VBox c_VerticalBox1;
	private global::Gtk.Toolbar c_Toolbar;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView c_ProjectTreeView;
	private global::Gtk.Label c_CreateMessageLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.c_RegenerateAction = new global::Gtk.Action ("c_RegenerateAction", null, global::Mono.Unix.Catalog.GetString ("Regenerate MonoDevelop Projects"), "regenerate");
		w1.Add (this.c_RegenerateAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Module Manager");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.c_VerticalBox1 = new global::Gtk.VBox ();
		this.c_VerticalBox1.Name = "c_VerticalBox1";
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='c_Toolbar'><toolitem name='c_RegenerateAction' action='c_RegenerateAction'/><separator/></toolbar></ui>");
		this.c_Toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/c_Toolbar")));
		this.c_Toolbar.Name = "c_Toolbar";
		this.c_Toolbar.ShowArrow = false;
		this.c_Toolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.c_Toolbar.IconSize = ((global::Gtk.IconSize)(1));
		this.c_VerticalBox1.Add (this.c_Toolbar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.c_Toolbar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.c_ProjectTreeView = new global::Gtk.TreeView ();
		this.c_ProjectTreeView.CanFocus = true;
		this.c_ProjectTreeView.Name = "c_ProjectTreeView";
		this.GtkScrolledWindow.Add (this.c_ProjectTreeView);
		this.c_VerticalBox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.GtkScrolledWindow]));
		w4.Position = 1;
		// Container child c_VerticalBox1.Gtk.Box+BoxChild
		this.c_CreateMessageLabel = new global::Gtk.Label ();
		this.c_CreateMessageLabel.Name = "c_CreateMessageLabel";
		this.c_CreateMessageLabel.Xpad = 10;
		this.c_CreateMessageLabel.Ypad = 5;
		this.c_CreateMessageLabel.Xalign = 0F;
		this.c_VerticalBox1.Add (this.c_CreateMessageLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.c_VerticalBox1 [this.c_CreateMessageLabel]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.Add (this.c_VerticalBox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 479;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
